export class PrismaClient {
  $connect = jest.fn().mockResolvedValue(undefined);
  $disconnect = jest.fn().mockResolvedValue(undefined);
  $transaction = jest.fn().mockImplementation((fn: any) => fn(this));
  auditLog = { create: jest.fn(), findMany: jest.fn(), count: jest.fn() };
  user = { create: jest.fn(), findUnique: jest.fn(), findFirst: jest.fn(), findMany: jest.fn(), update: jest.fn(), delete: jest.fn(), count: jest.fn() };
  securityQuestion = { create: jest.fn(), findMany: jest.fn(), deleteMany: jest.fn() };
  device = { create: jest.fn(), findUnique: jest.fn(), findFirst: jest.fn(), findMany: jest.fn(), count: jest.fn(), update: jest.fn(), delete: jest.fn(), deleteMany: jest.fn() };
  refreshToken = { create: jest.fn(), findFirst: jest.fn(), update: jest.fn(), updateMany: jest.fn(), deleteMany: jest.fn() };
  passwordHistory = { create: jest.fn(), findMany: jest.fn(), deleteMany: jest.fn() };
  idempotencyKey = { create: jest.fn(), findUnique: jest.fn(), findMany: jest.fn(), upsert: jest.fn(), delete: jest.fn(), deleteMany: jest.fn() };
  loginAttempt = { create: jest.fn(), count: jest.fn(), deleteMany: jest.fn() };
  role = { create: jest.fn(), findUnique: jest.fn(), findMany: jest.fn(), upsert: jest.fn() };
  permissionPoint = { create: jest.fn(), findUnique: jest.fn(), findMany: jest.fn(), upsert: jest.fn() };
  menu = { create: jest.fn(), findUnique: jest.fn(), findMany: jest.fn(), delete: jest.fn() };
  menuPermissionPoint = { createMany: jest.fn(), deleteMany: jest.fn() };
  rolePermissionPoint = { createMany: jest.fn(), deleteMany: jest.fn() };
  userRole = { create: jest.fn(), createMany: jest.fn(), findMany: jest.fn(), deleteMany: jest.fn(), upsert: jest.fn() };
  resource = { create: jest.fn(), findUnique: jest.fn(), findFirst: jest.fn(), findMany: jest.fn(), update: jest.fn(), delete: jest.fn(), count: jest.fn() };
  resourceHour = { create: jest.fn(), findMany: jest.fn(), deleteMany: jest.fn() };
  resourceClosure = { create: jest.fn(), findMany: jest.fn(), deleteMany: jest.fn() };
  travelTimeMatrix = { create: jest.fn(), findMany: jest.fn(), findFirst: jest.fn(), upsert: jest.fn(), deleteMany: jest.fn() };
  itinerary = { create: jest.fn(), findUnique: jest.fn(), findFirst: jest.fn(), findMany: jest.fn(), update: jest.fn(), delete: jest.fn(), count: jest.fn() };
  itineraryVersion = { create: jest.fn(), findMany: jest.fn(), findFirst: jest.fn(), count: jest.fn() };
  itineraryItem = { create: jest.fn(), findUnique: jest.fn(), findMany: jest.fn(), update: jest.fn(), delete: jest.fn(), deleteMany: jest.fn() };
  importBatch = { create: jest.fn(), findUnique: jest.fn(), findMany: jest.fn(), update: jest.fn() };
  importError = { create: jest.fn(), createMany: jest.fn(), findMany: jest.fn(), deleteMany: jest.fn() };
  mlModel = { create: jest.fn(), findUnique: jest.fn(), findFirst: jest.fn(), findMany: jest.fn(), update: jest.fn() };
  abAllocation = { create: jest.fn(), findMany: jest.fn(), upsert: jest.fn(), deleteMany: jest.fn() };
  notificationTemplate = { create: jest.fn(), findUnique: jest.fn(), findMany: jest.fn(), update: jest.fn() };
  notification = { create: jest.fn(), findUnique: jest.fn(), findMany: jest.fn(), update: jest.fn(), count: jest.fn() };
  outboxMessage = { create: jest.fn(), findMany: jest.fn(), update: jest.fn(), count: jest.fn() };
  userNotificationSetting = { findUnique: jest.fn(), upsert: jest.fn(), update: jest.fn() };
}
